language: android

jdk:
 - oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
    - extra

before_script:
 - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi armeabi-v7a
 - emulator -avd test -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &

script:
- ./gradlew connectedAndroidTest
