language: android

jdk:
 - oraclejdk7

android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
    - android-21
    - android-18
    - sys-img-armeabi-v7a-android-18

notifications:
  email: false

after_success:
  - .buildscript/deploy_snapshot.sh