language: android

jdk:
 - oraclejdk7

android:
  components:
    - build-tools-21.1.2
    - android-21

script:
  - ./gradlew clean check -Dpre-dex=false

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle