language: android

jdk:
 - oraclejdk7

android:
  components:
    - build-tools-21.1.2
    - android-21

notifications:
  email: false

before_script:
  - chmod +x gradlew
  
cache:
  directories:
    - $HOME/.gradle